#!/usr/bin/env python3

import sys
import json

from celery_utils.app import CONFIGS


def get_config(configs, args):
    if 1 == len(args):
        return configs

    # this allow to index lists in configurations
    if isinstance(configs, (tuple, list)):
        args[1] = int(args[1])

    return get_config(configs[args[1]], args[1:])


if __name__ == '__main__':
    try:
        print(json.dumps(get_config(CONFIGS, sys.argv)))
        sys.exit(0)
    except Exception as e:
        print("""error!
        {}""".format(e), file=sys.stderr)

        if 1 == len(sys.argv):
            print("""this should not happen!
            error = {}""".format(e),
                  file=sys.stderr)
            sys.exit(2)

        print("'{}' is not in configs!".format(' '.join(sys.argv[1:])),
              file=sys.stderr)
        sys.exit(1)
