#!/usr/bin/env python3

#
# This file is part of the celery-utils (https://github.com/e.sovetkin/celery-utils).
# Copyright (c) 2022 Jenya Sovetkin.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import sys
import json

from cu.app import CONFIGS


def get_config(configs, args):
    if 1 == len(args):
        return configs

    # this allow to index lists in configurations
    if isinstance(configs, (tuple, list)):
        args[1] = int(args[1])

    return get_config(configs[args[1]], args[1:])


if __name__ == '__main__':
    try:
        print(json.dumps(get_config(CONFIGS, sys.argv)))
        sys.exit(0)
    except Exception as e:
        print("""error!
        {}""".format(e), file=sys.stderr)

        if 1 == len(sys.argv):
            print("""this should not happen!
            error = {}""".format(e),
                  file=sys.stderr)
            sys.exit(2)

        print("'{}' is not in configs!".format(' '.join(sys.argv[1:])),
              file=sys.stderr)
        sys.exit(1)
